### ISSUE TITLE
$ is not a function

### ISSUE THREAD

**Issue by TheScree** [IonicaBizau/scrape-it#131]
```
const puppeteer = require('puppeteer');
const scrapeIt = require("scrape-it");

async function ssr(url) {
  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    headless: true
  });
  const page = await browser.newPage();
  await page.goto(url, {waitUntil: 'networkidle0'});
  const html = await page.content();
  await browser.close();
  return html;
}
let crowfallNews = ssr("https://crowfall.com/en/news/articles");

function Scrape(html) {
  console.log(html);
  let result = scrapeIt.scrapeHTML(html, {
      articles: {
        listItem: ".ArticleList__article",
        data: {
          // Get the article date and convert it into a Date object
          date: {
            selector: ".ArticleCard__date",
            convert: x => new Date(x)
          },
          // Get the title
          title: {
            selector: ".ArticleCard__title"
          },
          link: {
            selector: "a",
            attr: "href"
          },
          //get image url
          image: {
            selector: ".ArticleCard__img",
            attr: "style",
            convert: x => x.concat('https', x.slice(x.search("images.ctfassets.net")))
          },
          content: {
            selector: ".ArticleCard__description",
            closest: "p"
          }
        }
      }
    });
}
```

Returns "$ is not a function" on line  "let result = scrapeIt.scrapeHTML(html, "

Confirmed that the website is rendering inside puppeteer and contains the class selectors used above. Using latest version, just reinstalled.

Any thoughts?

**Comment by IonicaBizau** [comment]
Please post the full error stack to be able to inspect this...

**Comment by Stas-Buzunko** [comment]
"version": "5.1.4"
```
(node:4126) UnhandledPromiseRejectionWarning: TypeError: $ is not a function
    at /Users/bon/work/realt-scrapper/node_modules/scrape-it/lib/index.js:166:30
    at iterateObject (/Users/bon/work/realt-scrapper/node_modules/iterate-object/lib/index.js:28:17)
    at handleDataObj (/Users/bon/work/realt-scrapper/node_modules/scrape-it/lib/index.js:149:9)
    at Function.scrapeIt.scrapeHTML (/Users/bon/work/realt-scrapper/node_modules/scrape-it/lib/index.js:237:12)
    at Object.convert (/Users/bon/work/realt-scrapper/newBuildingsLun.js:192:38)
    at /Users/bon/work/realt-scrapper/node_modules/scrape-it/lib/index.js:228:34
    at iterateObject (/Users/bon/work/realt-scrapper/node_modules/iterate-object/lib/index.js:28:17)
    at handleDataObj (/Users/bon/work/realt-scrapper/node_modules/scrape-it/lib/index.js:149:9)
    at Function.scrapeIt.scrapeHTML (/Users/bon/work/realt-scrapper/node_modules/scrape-it/lib/index.js:237:12)
    at Timeout.setTimeout [as _onTimeout] (/Users/bon/work/realt-scrapper/newBuildingsLun.js:160:33)
```

**Comment by Stas-Buzunko** [comment]
in my case some selectors were missing. but why does it break everything?
