### ISSUE TITLE
scrapeHTML is not defined

### ISSUE THREAD

**Issue by tdukart** [IonicaBizau/scrape-it#164]
On scrape-it 5.3.0 I'm getting the following error:

```
/path/to/my/project/node_modules/scrape-it/lib/index.js:124
scrapeIt.scrapeHTML = scrapeHTML;
                      ^

ReferenceError: scrapeHTML is not defined
    at Object.<anonymous> (/path/to/my/project/node_modules/scrape-it/lib/index.js:124:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/todd.dukart/dev/vaccine-scraper/lib/getSpreadsheetUrl.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

The error doesn't manifest on 5.2.4.

**Comment by chetzof** [comment]
Just spent an hour trying to understand what is happening lol
The var is lowercase
`var scrapeHtml = require("scrape-it-core")`
and the assignment is uppercase
`scrapeIt.scrapeHTML = scrapeHTML`

rollback to 5.2.4 for now
