### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by z3to** [IonicaBizau/scrape-it#20]
When trying out your example from the blog I get this error:

```
$ node index.js
/Users/jparnow/Documents/Unicorns/node_modules/scrape-it/lib/index.js:155
                    let value = typpy(cOpt.how, Function) ? cOpt.how($elm) : $elm[cOpt.how]();
                                                                                 ^

TypeError: Cannot read property 'text' of undefined
    at iterateObj (/Users/jparnow/Documents/Unicorns/node_modules/scrape-it/lib/index.js:155:82)
    at iterateObject (/Users/jparnow/Documents/Unicorns/node_modules/iterate-object/lib/index.js:25:17)
    at handleDataObj (/Users/jparnow/Documents/Unicorns/node_modules/scrape-it/lib/index.js:119:13)
    at Function.scrapeIt.scrapeHTML (/Users/jparnow/Documents/Unicorns/node_modules/scrape-it/lib/index.js:172:12)
    at req (/Users/jparnow/Documents/Unicorns/node_modules/scrape-it/lib/index.js:28:27)
    at Tinyreq (/Users/jparnow/Documents/Unicorns/node_modules/cheerio-req/lib/index.js:21:9)
    at opt_callback (/Users/jparnow/Documents/Unicorns/node_modules/tinyreq/lib/index.js:57:9)
    at IncomingMessage.res.on.on.on (/Users/jparnow/Documents/Unicorns/node_modules/tinyreq/lib/index.js:89:13)
```

I’m using Node v6.0.0

It would be great if this could be fixed.

**Comment by IonicaBizau** [comment]
Well, actually the example was wrong (related discussion: #15). Sorry for that.

**Comment by z3to** [comment]
Thank you very much!

**Comment by IonicaBizau** [comment]
@z3to In #23 I added an additional fix to this: an error explicitly saying you have to pass the `listItem`, `selector` or have a context. :ship: **`3.1.0`** :tada:
