### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by gpapin** [IonicaBizau/scrape-it#35]
I've been using this module for a couple of weeks now and recently I get this error when using it : 
```
{ Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }
```

I understand the connection refuse bit  - which is totally expected btw because nothing listen on 127.0.0.1:443 ... but why is it trying to reach that address when I ask for the internet ?

Here is a small snippet that I use to isolate the issue from other bits and pieces of my app: 

```
const scrapeIt   = require('scrape-it');
scrapeIt("http://korben.info/", {
	posts: {
		listItem: ".post",
		data: {
			title: {
				selector: '.post-title'
			}
		}
	}
}, (err, result) => {
	if(err){
		console.log("ERROR fecthing site");
		console.log(err);
	}else{
		console.log(result);
	}
});
```

I know it's likely to be something to do with my setup but I struggling to see where it could came from... especially since I haven't touch anything over the week end...

**Comment by gpapin** [comment]
Nothing to do with scrape-it as suspected since this doesn't work as well...
```
var req = require("cheerio-req");


req("google.fr", function (err, $, res, body) {
    if (err) {
        console.log(err);
    }
});
```

**Comment by gpapin** [comment]
[I moved the issue](https://github.com/IonicaBizau/cheerio-req/issues/5)
