### ISSUE TITLE
Firebase Functions / Cheerio

### ISSUE THREAD

**Issue by divanvb** [IonicaBizau/scrape-it#88]
Hi

I'm trying to deploy a function to firebase but as soon as I try, I receive this error with the package:
`node_modules/scrape-it/lib/index.d.ts(9,35): error TS2304: Cannot find name 'CheerioSelector'.
node_modules/scrape-it/lib/index.d.ts(22,41): error TS2304: Cannot find name 'CheerioStatic'.`

Any idea how I can fix this?

**Comment by IonicaBizau** [comment]
That seems to be TypeScript related. /cc #80 @AndrewNeo Maybe you can take a look.

**Comment by AndrewNeo** [comment]
Try making `@types/cheerio` a direct dependency on your project and see if that solves the problem.

**Comment by divanvb** [comment]
I'll have a look. 

@AndrewNeo Are you talking about adding it directly to the project package.json? If so then it also doesn't worked because that's the first thing I've tried :'(

**Comment by divanvb** [comment]
@AndrewNeo How would you add the `@types/cheerio` directly as I've tried npm installing it directly if that's what you meant with your previous comment.

**Comment by divanvb** [comment]
@AndrewNeo So I've just installed the `@types/cheerio` like you suggested a dependency, and it seems to build now. I'm going to deploy now and then will report back if it was successful.

**Comment by divanvb** [comment]
Upon deploying and trying to execute the function, I get an error stating
`AssertionError: protocol mismatch
    at parseOptions (/user_code/node_modules/scrape-it/node_modules/follow-redirects/create.js:131:10)
    at Object.H.request (/user_code/node_modules/scrape-it/node_modules/follow-redirects/create.js:108:19)
    at Function.tinyreq (/user_code/node_modules/scrape-it/node_modules/tinyreq/lib/index.js:73:65)
    at cheerioReq (/user_code/node_modules/scrape-it/node_modules/cheerio-req/lib/index.js:20:27)
    at scrapeIt (/user_code/node_modules/scrape-it/lib/index.js:25:5)
    at exports.getArenas (/user_code/lib/index.js:27:5)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:26:41)
    at /var/tmp/worker/worker.js:671:7
    at /var/tmp/worker/worker.js:655:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)`

Any idea what this could be?

**Comment by divanvb** [comment]
Nevermind, it's working now. Had to include http for it to recognize it!

**Comment by IonicaBizau** [comment]
Cool! 👍
